# apps/spring-boot/overlays/dev/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
namespace: gitops-app-prod
namePrefix: prod-
commonLabels:
  env: prod
# 이미지 태그 오버라이드 (CI에서 자동 업데이트)
images:
  - name: gitops-app # : gitops-app 테스트 이미지
    newName: bovo22/gitops-app
    newTag: latest

replicas:
  - name: gitops-app
    count: 1
